services:
  containers-test:
    build:
      context: ../..
      dockerfile: containers/docker/Dockerfile
    image: r2bewi-containers-build:latest
    working_dir: /workspace
    volumes:
      - ../..:/workspace
    command: bash containers/src/tests/lint.sh

  containers-build:
    build:
      context: ../..
      dockerfile: containers/docker/Dockerfile
    image: r2bewi-containers-build:latest
    container_name: r2bewi-containers-build
    working_dir: /workspace
    user: root
    stdin_open: true
    tty: true
    volumes:
      - ../..:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
